### ISSUE TITLE
Method "GET Institutions"

### ISSUE THREAD

**Issue by kevinlove** [nybgvh/IH-API#1]
In the documentation, all parameters are described as optional, although, this query returns a 400:

http://sweetgum.nybg.org/science/api/v1/institutions/search

```{"meta":{"hits":0,"code":400,"message":"Error, invalid query request."}}```

It appears that this method works for my purpose, but is not documented:

http://sweetgum.nybg.org/science/api/v1/institutions

Cheers!

**Comment by nybgvh** [comment]
That's correct.  We've updated the documentation.

To get all available institutions use: 
http://sweetgum.nybg.org/science/api/v1/institutions

To get all staff use:
http://sweetgum.nybg.org/science/api/v1/staff

Thanks!
