### ISSUE TITLE
GET /api/institutions/:code

### ISSUE THREAD

**Issue by mjy** [nybgvh/IH-API#3]
```
When I GET for a single institution code (e.g. "ALA")
   then I return the JSON for that single record (i.e. not an array)
```

As I understand it :code is the unique identifier for an institution.  Providing a REST-like interface to accessing the single record by its "id" (== code) would be very useful.

**Comment by nybgvh** [comment]
Hi Matt,

Thank you for your suggestion. This endpoint has now been included and documented in the wiki.

Best,
NYBG
