### ISSUE TITLE
Wiki updates

### ISSUE THREAD

**Issue by kevinlove** [nybgvh/IH-API#4]
Hello,

I've made some API examples using R that I'd like to contribute to the wiki. I'll include them inline here, but it would be great if I could commit them via a pull request or as a collaborator.

Thanks!

https://github.com/nybgvh/IH-API/wiki/GET-Staff

## R 

Using the API with R:

```r
      library(jsonlite)
      url <- "http://sweetgum.nybg.org/science/api/v1/staff/search?country=bolivia&sort=lastName&limit=10"
      df <- fromJSON(url)$data
      paste0(df$firstName," ",df$lastName)
```

https://github.com/nybgvh/IH-API/wiki/GET-Institutions

## R 

Using the API with R:

```r
      library(jsonlite)
      url <- "http://sweetgum.nybg.org/science/api/v1/institutions/search?country=india"
      df <- fromJSON(url)$data
      df$organization
```

**Comment by nybgvh** [comment]
Hi Kevin,

Sounds great! We've added you as a collaborator.

NYBG

**Comment by kevinlove** [comment]
Added these examples to the wiki, thanks!
