### ISSUE TITLE
Clarify “beta”

### ISSUE THREAD

**Issue by timrobertson100** [nybgvh/IH-API#5]
Hi folks

This is documented as beta. Can you please comment on what a consumer can reasonably expect in terms of stability?

I am interested in syncing against this to update the very outdated IH records shown in GrSciCol that GBIF resurrected. Any thoughts, concerns or indications of support for that idea most welcome.

Thanks

**Comment by nybgvh** [comment]
Hi Tim,

Sorry, the home page of wiki needs to be updated. This is a stable version of API and you may use it update GrSciCol records.

Thanks
