### ISSUE TITLE
error when using nearbysearch

### ISSUE THREAD

**Issue by abubelinha** [nybgvh/IH-API#8]
https://sweetgum.nybg.org/science/api/v1/institutions/nearbysearch?lat=41.9970898&lon=2.927948&radius=51

#### output:

> **Fatal error**: Uncaught Error: Call to undefined method Error::displayError() in /home/emu/nybgweb/www-live/htdocs/science/api/v1/Slim/Institutions.php:229 Stack trace: #0 /home/emu/nybgweb/www-live/htdocs/science/api/v1/index.php(59): Institutions->nearbySearch(Object(Slim\Slim)) #1 [internal function]: {closure}() #2 /home/emu/nybgweb/www-live/htdocs/science/api/v1/Slim/Route.php(468): call_user_func_array(Object(Closure), Array) #3 /home/emu/nybgweb/www-live/htdocs/science/api/v1/Slim/Slim.php(1357): Slim\Route->dispatch() #4 /home/emu/nybgweb/www-live/htdocs/science/api/v1/Slim/Middleware/Flash.php(85): Slim\Slim->call() #5 /home/emu/nybgweb/www-live/htdocs/science/api/v1/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call() #6 /home/emu/nybgweb/www-live/htdocs/science/api/v1/Slim/Slim.php(1302): Slim\Middleware\MethodOverride->call() #7 /home/emu/nybgweb/www-live/htdocs/science/api/v1/index.php(118): Slim\Slim->run() #8 {main} thrown in **/home/emu/nybgweb/www-live/htdocs/science/api/v1/Slim/Institutions.php** on line **229**

Looks like the error comes when requested `radius` is bigger than 50.
It would be better to return a json answer with empty `data` [list] plus some kind of error message.

Thanks @nybgvh

**Comment by nybgvh** [comment]
Hi,

Thanks for the inquiry. We have fixed this bug that did not allow error responses to display properly. Prior to issue, it did handle such cases:

Example: When radius is larger than 50.

https://sweetgum.nybg.org/science/api/v1/institutions/nearbysearch?lat=41.9970898&lon=2.927948&radius=67

{
  "meta": {
    "hits": 0,
    "code": 200,
    "message": "AREA_TOO_LARGE"
  }
}

Thanks,
Science Team
